### ISSUE TITLE
API Package distribution 

### ISSUE THREAD

**Issue by qunabu** [EscolaLMS/API#1]

**Comment by MWL91** [comment]
This package should be independent from Laravel.
Anyone who wants to use full or just a part of features should be able to do that.

I would like to split it as following:

- Core - package that contains all our core features like Repositories, Traits, Dtos, Basic interface - all that would be required without even single course solution. Using this pack may be also useful to create new laravel project intependent from LMS.
- Course - package contains all features of courses and learning - all that will be available with configurable endpoints. Also here we'll have any integrations with Users, that may be assigned to specific course. 
- Authentication - package used for authentication - if someone wants to have their own auth system, there will be not issue with our solution, but if you want to have users, login, social login, profiles out of the box, that will be available for you.
- Discussions - package that may be used for implement forum and all discussions according ANY model (including course, social action ect.)
- Rewards - package used for gain and spent points, also for generate certificates and any other rewards that may be required
- Plans - package used for plan courses in specific collections. It may be education path, it may be course access levels
- Repository - package used for create repositories of contents (User generated content, admin uploaded contents) - may be similar to wordpress media
- Marketing - push notifications, emails, ect.
- Stats - package for statistics

**Comment by MWL91** [comment]
All those package will have endpoints and Controllers that may be used, and will be enabled by default, but in any case user will be able to create their own solutions simply created by services by DI.

Endpoints will be published and editable outside vendor.

**Comment by qunabu** [comment]
@MWL91 please add this somewhere here https://coggle.it/diagram/X_7Wrx2p4gfbxv0f/t/escola-headless-lms
