### ISSUE TITLE
`Passport` migration issue

### ISSUE THREAD

**Issue by qunabu** [EscolaLMS/API#12]
See screenshot. 

_Issue created from a [Mattermost message](https://mattermost.etd24.pl/_redirect/pl/d49tf9asujfkuj77zaiut9dd8w) *by @qunabu*._

**Comment by qunabu** [comment]
Reproduce `make init` on `develop` branch 

![image](https://user-images.githubusercontent.com/214608/113255684-66c17100-92c8-11eb-9b8d-07d1e7e012be.png)

**Comment by qunabu** [comment]
Refers to https://github.com/EscolaLMS/Core/pull/8

**Comment by MWL91** [comment]
@qunabu bug is temporary fixed by rollback oauth migrations. `make init` works, however we need to refactor core to make it works with oauth migrations
