### ISSUE TITLE
Public Dockerfile for escolalms/php:8-prod

### ISSUE THREAD

**Issue by JohnGale87** [EscolaLMS/API#268]
The Dockerfile used in this repo is based off `escolalms/php:8-prod`

But I cant see any public Dockerfile for that image. It seems to be a modified version of [devilbox/php-fpm:8.0-prod](https://github.com/cytopia/devilbox) but I can't really tell exactly what the modifications are.

Please can we see what the custom modifications are?

**Comment by qunabu** [comment]
All the images used are here https://hub.docker.com/search?q=escolalms 

The one you're referring to is https://hub.docker.com/layers/escolalms/php/8-prod/images/sha256-5c4c041d3b24050e0a9a72ba72bd427d93a1f4ad575f09a1f0c43321ee0d6a15?context=explore

Repository is here https://github.com/EscolaLMS/Laravel-Docker/blob/8-prod/Dockerfile

**Comment by JohnGale87** [comment]
Thank you for the speedy response! Sorry I'd missed that.

Do you have a help forum or email address I can use for further questions or is github issues the best place for things like that?
