### ISSUE TITLE
nginx routing

### ISSUE THREAD

**Issue by JohnGale87** [EscolaLMS/API#269]
When I run the application locally using `php artisan serve` I can access the application in my browser by navigating to urls like `http://127.0.0.1:8000/api/config` or `http://127.0.0.1:8000/api/events` and I see a page of JSON data as I would expect so everything seems like it is working.

However, if I run `make init` (or later after having done that once `docker composer up`) then I can't acess those url paths anymore (I adjust the url host to account for the change in port) ... but when I visit `http://localhost:1001/api/config` and `http://localhost:1001/api/events` both give me a nginx error:
```
404 Not Found
---
nginx/1.23.3
```
(e.g. [https://images.app.goo.gl/Jv3VFF1oJ6v8UAT7A](https://images.app.goo.gl/Jv3VFF1oJ6v8UAT7A))

I've tried it via `docker compose` as well as `docker build` / `docker run` and have a similar problem everytime.

Regardless of if I use `php artisan server` or Doceker I can always access the `/` root path and I get the default Laveral 404 page (e.g. [https://images.app.goo.gl/ACyvjgZuojj2SKsv5](https://images.app.goo.gl/ACyvjgZuojj2SKsv5)). But this also happens on [https://api.escolalms.com](https://api.escolalms.com) so I assume it is right.

For additional context just in case it helps, my goal is to get this running on Google Cloud Run using a Postgres database in Google Cloud SQL. To date, I have the app and database both deployed, the root of the Cloud Run instance shows the Laveral 404 default page, but the `/api` paths show the nginx error. So my assumption is that if I can make it work in Docker on my local machine it should work in Doceker on cloud run too.

Any assistance you can provide will be greatfully recieved.

**Comment by JohnGale87** [comment]
My assumption is that there is something wrong with the nginx configuration / setup ? As I believe that when I hit `/api/events` it is nginx's job to route that into index.php and then the Laveral framework handles it from there and that doesn't seem to be happening. 

I could also just be wrong and it is something else.

**Comment by qunabu** [comment]
I've just updated files regarding those issues, can you pull the changes and try to again

**Comment by JohnGale87** [comment]
@qunabu thanks for your responsiveness on this. I'm working on something else right now so it'll take me a few days to get back onto this and verify but just wanted to let you know I've not lost interest and will be back on this as soon as I can.

**Comment by qunabu** [comment]
@JohnGale87 no problem, don't hesitate  to ask anything

**Comment by qunabu** [comment]
I think I've come across the problem 
I've misconfigured CORS so any call to `api` without `Origin` or/and `Referer` might return 404 from nginx. I'm going to fix this soon

**Comment by JohnGale87** [comment]
So coincidental that you also looked at this yesterday, I was doing the same!

Looks like I should have been more patient because my most recent changes look a lot like your #270 🤦‍♂️  but I'm glad really. It means I wasn't too far off / got it right. Proved to myself that I really do understand it 😂 

Anyway, back on topic, I came back to let you know that I never could get nginx working but in your recent updates to [add Caddy into source control](https://github.com/EscolaLMS/API/compare/b19760e95d9958a4b026e23de5f73ede5d576184...9836b8b99d1e610e6e12a43ced038b8024290191) it gave me some new ideas and after a whole lot of trial and error and different configurations I managed to get this repo deployed onto GCP Cloud Run (with Caddy), a GCP Memorystore Redis cache and a GCP Cloud SQL Postgres database.

🥳 

I'm sure there is still a bit of work left to do to get it working flawlessley but I am able to call the /api/config and /api/event endpoints and get back data which has been my "healthcheck" to date.

**Comment by JohnGale87** [comment]
@qunabu just merging your changes with mine and I had a question.

https://github.com/EscolaLMS/API/pull/270/files#diff-dd2c0eb6ea5cfc6c4bd4eac30934e2d5746747af48fef6da689e85b752f39557L13

Was the removal of this ini file intentional? Was that only used for nginx ? It wasn't clear from the name.

**Comment by qunabu** [comment]
This was duplication of [`init.sh`](https://github.com/EscolaLMS/API/blob/develop/init.sh) it shouldn't be there in the first place

**Comment by qunabu** [comment]
> So coincidental that you also looked at this yesterday, I was doing the same!
> 
> Looks like I should have been more patient because my most recent changes look a lot like your #270 🤦‍♂️ but I'm glad really. It means I wasn't too far off / got it right. Proved to myself that I really do understand it 😂
> 
> Anyway, back on topic, I came back to let you know that I never could get nginx working but in your recent updates to [add Caddy into source control](https://github.com/EscolaLMS/API/compare/b19760e95d9958a4b026e23de5f73ede5d576184...9836b8b99d1e610e6e12a43ced038b8024290191) it gave me some new ideas and after a whole lot of trial and error and different configurations I managed to get this repo deployed onto GCP Cloud Run (with Caddy), a GCP Memorystore Redis cache and a GCP Cloud SQL Postgres database.
> 
> 🥳
> 
> I'm sure there is still a bit of work left to do to get it working flawlessley but I am able to call the /api/config and /api/event endpoints and get back data which has been my "healthcheck" to date.

would you be able to share with us how to setup this on GCP, w would be able to create a terraform as we did for AWS https://github.com/EscolaLMS/aws-ecs-terraform 

@gutarow have a look ☝️

**Comment by JohnGale87** [comment]
> This was duplication of [`init.sh`](https://github.com/EscolaLMS/API/blob/develop/init.sh) it shouldn't be there in the first place

Maybe the link didn't work right, it was this line I was refering to:
`cp docker/conf/php/xxx-devilbox-default-php.ini /usr/local/etc/php/conf.d/xxx-devilbox-default-php.ini`

**Comment by JohnGale87** [comment]
> would you be able to share with us how to setup this on GCP

Yes, but not right away. I need to refactor and anonymize my scripts.

**Comment by qunabu** [comment]
@JohnGale87 can you confirm this is resolved ?

**Comment by qunabu** [comment]
@JohnGale87 thanks for catching the issue with php.ini, we've just discovered a problem with uploading big files.
