### ISSUE TITLE
Assertion failed whilst trying to login

### ISSUE THREAD

**Issue by shdpl** [EscolaLMS/API#30]
Branch: devel
Endpoint: /api/auth/login
Problem: "Code 422: assert(): assert($user instanceof AuthUser) failed"

How to reproduce:
curl -X 'POST' \
  'http://localhost:1000/api/auth/login?email=admin%40escola-lms.com&password=secret' \
  -H 'accept: application/json' \
  -H 'X-CSRF-TOKEN: ' \
  -d ''

**Comment by shdpl** [comment]
To give a little bit more context:
*\App\Models\User* is expected to be an instance of *\EscolaLms\Auth\Models\User*
which inherits from *\Escolalms\Core\Models\User* which is not an instance of *\EscolaLms\Auth\Models\User*

Shall we remove that assertion and make a separate test for the factory?

**Comment by qunabu** [comment]
@shdpl please check now if it is fixed

**Comment by shdpl** [comment]
Yes, ```use EscolaLms\Auth\Models\User as CoreUser;``` did the trick. if you'd like to port it to Laravel-Docker-Tools which is what i needed to do, take a look on https://github.com/EscolaLMS/Laravel-Package-Docker-Development-Tools/pull/6

**Comment by HerbertIV** [comment]
The problem not returned
