### ISSUE TITLE
e2e test student attend course

### ISSUE THREAD

**Issue by qunabu** [EscolaLMS/API#36]
## e2d test student attend course

1. login
2. find course by price, free one 
3. add it to basket 
4. purchase 
5. start course 
6. check if course is on list of your courses in progress 
7. progress each lesson & topic 
8. update progress 
9. finish course 
10. check if course is on list of your finished courses

_Originally posted by @qunabu in https://github.com/EscolaLMS/API/discussions/33#discussioncomment-741415_

**Comment by pa-cholek** [comment]
This test exists partially, but doesn't update course progress
