### ISSUE TITLE
wrong url for images

### ISSUE THREAD

**Issue by mcholcha** [EscolaLMS/API#74]
GET https://api.escolalms.com/api/courses/2/program

data->lessons[]->topics[]->topicable->url

`https://api.escolalms.com//storage/course/2/topic/145/image/UDFlDNdxebwTKmVjYOxcZFoso8IYXT8JMTer4oHg.jpg`

double slash

**Comment by pa-cholek** [comment]
Fixed
- removed slash from APP_URL in `.env` file
- run `php artisan storage:link`
