### ISSUE TITLE
packages must dispatch events 

### ISSUE THREAD

**Issue by qunabu** [EscolaLMS/API#91]
all of the following packages must disptch event that It is compatible with [Templates](https://github.com/EscolaLMS/Templates) event contract (ask @pa-cholek about detials) 

**Auth** 
* Login
* Logout 
* Account Registered
* Account Confirmed (link clicked, or manualy from admin panel) 
* User added to group 
* User removed from group 
* Reset password request 
* Password changed 

**Courses**
* Coursed published 
* Course dealine soon (x days till deadline) 
* Course access started (when timespan set)  
* Course access finished (when timespan set)
* Course assigned (course assigned to user) 
* Course finished (progress === 100)
* Course started (progres from 0 to > 0) 
* Topic Finished 

**TopicTypes** 
* TopicType Changed (new or update) 

**Payments**
* Payment Registered
* Payment Success 
* Payment Failed 
 
**Cart** 
* Order success 

**Permissions**
* Role changed (new or update)
* Role removed 

**Settings** 
* Package config updated 

- [ ] add dispatch(event())
- [ ] tests

**Comment by HerbertIV** [comment]
Close
