### ISSUE TITLE
lack of permissions

### ISSUE THREAD

**Issue by mcholcha** [EscolaLMS/API#94]
This is general task for all the packages 

- [ ] each package should have permissions renamed to [follow the pattern](https://github.com/EscolaLMS/GH-Actions-Template#permissions-naming-pattern)
- [ ] permissions names are in Policies, Requests (not always), and Permissions seeders. example [1](https://github.com/EscolaLMS/Notifications/blob/main/database/seeders/NotificationsPermissionsSeeder.php), [2](https://github.com/EscolaLMS/Notifications/blob/main/src/Http/Requests/NotificationsRequest.php), [3](https://github.com/EscolaLMS/Categories/blob/main/src/Policies/CategoryPolicy.php) 
- [ ] some packagea are missing some permissions they must be implemented 

There are no permissions to block access in the admin panel for:
courseList

h5pList
h5pDetails

scormList
scormDetails

pageList
pageDetails

templateList
templateDetails

categoryList

roleList

**Comment by qunabu** [comment]
@KrzysztofDziedziechEscolasoft please let @mcholcha know once those are implemented
